### ISSUE TITLE
pyproject-fmt 2.21.2 ImportError After toml-fmt-common 1.3.3 Release

### ISSUE THREAD

**Issue by GnoX** [tox-dev/toml-fmt#355]
### 📝 Description

In `toml-fmt-common` **1.3.3**, the private symbol `_build_cli` was renamed to public `build_cli`. `pyproject-fmt` **2.21.2** still imports the underscore name, so every invocation crashes at import time before parsing argv. This affects all install paths that resolve `toml-fmt-common` freely (`uvx`, `pre-commit` / `prek` hook envs, fresh `pip install`), while environments pinned to `toml-fmt-common<1.3.3` remain unaffected. Version 2.21.1 and earlier of `pyproject-fmt` hit the same import path and are equally broken against 1.3.3.

```
ImportError: cannot import name '_build_cli' from 'toml_fmt_common'
(.../toml_fmt_common/__init__.py). Did you mean: 'build_cli'?
```

#### Root Cause

PR [tox-dev/toml-fmt#320](https://github.com/tox-dev/toml-fmt/pull/320) ("deduplicate table formatting CLI arguments") landed in [toml-fmt-common/1.3.3](https://github.com/tox-dev/toml-fmt/releases/tag/toml-fmt-common%2F1.3.3) and promoted `_build_cli` to `build_cli` without keeping a deprecation alias. `pyproject-fmt` was updated as well in the same PR, but not released yet leaving all currently released versions broken as they don't have this pin so clients have to explicitly pin `toml-fmt-common<1.3.3` which could be annoying for projects using it as pre-commit hooks.

```python
# pyproject_fmt/__main__.py (2.21.2)
from toml_fmt_common import ArgumentGroup, FmtNamespace, TOMLFormatter, _build_cli, run
```

`pyproject-fmt`'s wheel declares `toml-fmt-common` without an upper bound, so `pip` / `uv` resolve 1.3.3 on any cold install - the contract between the two sibling packages in `tox-dev/toml-fmt` is broken at the metadata level.

Clients using pre-commit have to pin the version explicitly to use all versions 2.21.2 and lower:
```diff
    - repo: https://github.com/tox-dev/pyproject-fmt
      rev: v2.21.2
      hooks:
          - id: pyproject-fmt
+           additional_dependencies: [toml-fmt-common<1.3.3]
```

#### Affected Versions

- `toml-fmt-common` **1.3.3**: Breaks every `pyproject-fmt` 2.x release that imports `_build_cli`
- `toml-fmt-common` **1.3.2** and earlier: Unaffected
- `pyproject-fmt` **2.21.2** (and earlier versions 2.14.1 and up): Fails against 1.3.3

#### Reproducer

```bash
# Fails on 1.3.3
uvx --isolated pyproject-fmt==2.21.2 --version
# ImportError: cannot import name '_build_cli' from 'toml_fmt_common'

# Works on 1.3.2
uvx --isolated --with 'toml-fmt-common<1.3.3' pyproject-fmt==2.21.2 --version
# pyproject-fmt (2.21.2)
```

#### Suggested fix

Ideally, `toml_fmt_common` should add compatibility alias
```python
_build_cli = build_cli
```` 
To keep previous versions from crashing without explicit pinning of different packages as it could be annoying when used from pre-commit hooks.

`pyproject-fmt` should also probably add a pin to keep this from happening in the future.

### 📄 Input pyproject.toml

```toml
Not relevant.
```

### ✅ Expected output

```toml

```

### ❌ Actual output

```toml

```

### 🏷️ Version

pyproject-fmt 2.14.1 -> 2.21.2

**Comment by Diegorro98** [comment]
Same here, at pyproject-fmt pre-commit hook:
```
pyproject-fmt............................................................Failed
- hook id: pyproject-fmt
- exit code: 1

  Traceback (most recent call last):
    File "/home/vsts/.cache/prek/hooks/python-pr64v0gFJ1nA182cQ2j4/bin/pyproject-fmt", line 4, in <module>
      from pyproject_fmt.__main__ import runner
    File "/home/vsts/.cache/prek/hooks/python-pr64v0gFJ1nA182cQ2j4/lib/python3.12/site-packages/pyproject_fmt/__init__.py", line 5, in <module>
      from .__main__ import runner as run
    File "/home/vsts/.cache/prek/hooks/python-pr64v0gFJ1nA182cQ2j4/lib/python3.12/site-packages/pyproject_fmt/__main__.py", line 9, in <module>
      from toml_fmt_common import ArgumentGroup, FmtNamespace, TOMLFormatter, _build_cli, run  # noqa: PLC2701
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ImportError: cannot import name '_build_cli' from 'toml_fmt_common' (/home/vsts/.cache/prek/hooks/python-pr64v0gFJ1nA182cQ2j4/lib/python3.12/site-packages/toml_fmt_common/__init__.py). Did you mean: 'build_cli'?

```

This is a huge problem for CI/CD pipelines

**Comment by gaborbernat** [comment]
Ack will fix soon.

**Comment by bonastreyair** [comment]
A quick fix win might be to release a new version of the `toml-fmt-common` with `build_cli` also exposed as `_build_cli`, to regain retro compatibility and require 0 changes on any CI/CD pipelines.

..and after that, then focus on that bundling MR #360 ?

WDYT?

**Comment by bonastreyair** [comment]
After the fix and release, it is still failing due to `argparse.ArgumentError: argument --table-format: conflicting option string: --table-format`

**Comment by GnoX** [comment]
Yeah, I didn't verify whether re-exposing `_build_cli` would actually fix it in my initial report.

#320 also added registration for several keys on the same argparse group - it registers the four flags in [`build_cli`](https://github.com/tox-dev/toml-fmt/blob/toml-fmt-common%2F1.3.4/toml-fmt-common/src/toml_fmt_common/__init__.py#L264-L298) then [calls `of.add_format_flags(format_group)`](https://github.com/tox-dev/toml-fmt/blob/toml-fmt-common%2F1.3.4/toml-fmt-common/src/toml_fmt_common/__init__.py#L300), which re-enters [`pyproject_fmt/__main__.py:84-107`](https://github.com/tox-dev/toml-fmt/blob/pyproject-fmt%2F2.21.2/pyproject-fmt/src/pyproject_fmt/__main__.py#L84-L107) and re-registers the same flags. I now verified that if we remove the four duplicate `parser.add_argument(...)` blocks for `--table-format`, `--expand-tables`, `--collapse-tables`, `--skip-wrap-for-keys` inside [`PyProjectFormatter.add_format_flags`](https://github.com/tox-dev/toml-fmt/blob/pyproject-fmt%2F2.21.2/pyproject-fmt/src/pyproject_fmt/__main__.py#L84-L107) (now registered by [`toml_fmt_common.build_cli`](https://github.com/tox-dev/toml-fmt/blob/toml-fmt-common%2F1.3.4/toml-fmt-common/src/toml_fmt_common/__init__.py#L264-L298)), it won't crash. This won't fix previous versions though, this has to be changed in `pyproject-fmt` which is a problem.

**edit**: What would fix it is set up a `conflict_handler="resolve"` in the format group in [`toml_fmt_common/__init__.py:249`](https://github.com/tox-dev/toml-fmt/blob/toml-fmt-common%2F1.3.4/toml-fmt-common/src/toml_fmt_common/__init__.py#L249) which won't re-register it if it's already registered.

**Comment by bonastreyair** [comment]
If that does the patching for now then its perfect!
It would solve multiple people having CI failures due to that!

**Comment by GnoX** [comment]
It would certainly help us as we use templates to distribute `pre-commit` hooks so getting it downstream to around 40 projects at once is a lot of effort we would like to avoid if possible.

I tested that that conflict handler would resolve it without changing any behavior for all previous versions and yet unreleased `pyproject-fmt` changes, but it is possible that it could make some unexpected bugs in the future as it silently overrides mismatches so I'm generally not a fan of this option. This seems to be the easiest way to solve our current problems though.

**Comment by gaborbernat** [comment]
Fixed in **`toml-fmt-common` 1.3.5** (just released to PyPI) — no changes needed on your side. Pinned `pyproject-fmt`/`tox-toml-fmt` versions, `uvx`, `pipx`, and pre-commit/prek hooks will resolve `toml-fmt-common` 1.3.5 on a fresh install and work again.

What went wrong: 1.3.3 renamed `_build_cli` → `build_cli` **and** moved the shared formatting flags (`--table-format`, `--expand-tables`, …) into `build_cli`. 1.3.4 restored the `_build_cli` alias but not the flag move, so released consumers still crashed on the duplicate `--table-format`. 1.3.5 gives the formatting argument group `conflict_handler="resolve"`, so a consumer that re-registers those flags overrides them instead of raising — restoring compatibility with every released version.

Verified against `pyproject-fmt` 2.14.1–2.21.2 and `tox-toml-fmt` 1.8.0–1.9.3 on live PyPI, including real format runs.

Thanks @GnoX for the precise diagnosis and the `conflict_handler="resolve"` suggestion, and @bonastreyair / @Diegorro98 for confirming the impact. Sincere apologies for the breakage and the CI/CD disruption it caused — a release-time contract check against published consumers is being added so a common release can't break existing installs like this again.

**Comment by acdha** [comment]
@gaborbernat thank you for the rapid response, we really appreciate that you're providing a community service.
